source 'http://rubygems.org'
ruby '2.3.0'
gem 'sinatra'
gem 'sinatra-partial'
gem 'data_mapper'
gem 'dm-sqlite-adapter', :group => :development
gem 'dm-postgres-adapter'
gem 'slim'
gem 'tilt', '~> 1.4.1' #temporary fix
gem 'omniauth-openid'
gem 'omniauth-steam'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'em-websocket'
gem 'rack-flash3'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'thin'
gem 'em-hiredis'
gem 'bson_ext'
gem 'rake'
gem 'eventmachine'
gem 'rspec'
group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
end